services:
  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: videogamescatalogue-sql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      SA_PASSWORD: "YourStrong!Passw0rd"
    ports:
      - "1433:1433"
    volumes:
      - sql-data:/var/opt/mssql

volumes:
  sql-data:
